[package]
name = "board-mks-esp32-foc-v1"
description = "Typed compile-time MKS ESP32 FOC V1.0 board package"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
alumina-board.workspace = true
alumina-protocol.workspace = true

[dev-dependencies]
alumina-capability.workspace = true

[lints]
workspace = true
