// @generated by tools/alumina-brotli-decoder/build-assets.sh; do not edit.

/// SHA-256 over [`WEB_BUNDLE_MANIFEST`].
pub const WEB_BUNDLE_DIGEST: Digest = digest("8588ad72e8a4b516d1299060f9ad470d9d1db397bf6a4c96a3fb99b18cef9e49");

const INDEX: &[u8] = include_bytes!("../assets/index.html");
const BOOTSTRAP: &[u8] = include_bytes!("../assets/alumina-bootstrap.js");
const DECODER_WASM: &[u8] = include_bytes!("../assets/alumina-brotli-decoder_bg.wasm");
const MODULE_BROTLI: &[u8] = include_bytes!("../assets/alumina-interface.js.br");
const WASM_BROTLI: &[u8] = include_bytes!("../assets/alumina-interface_bg.wasm.br");
const WORKER: &[u8] = include_bytes!("../assets/alumina-worker.js");
const FAVICON: &[u8] = include_bytes!("../assets/favicon.ico");
const BUNDLE_MANIFEST: &[u8] = include_bytes!("../assets/bundle.toml");

/// Complete finite public asset table in exact route order.
pub const WEB_ASSETS: &[EmbeddedWebAsset] = &[
    EmbeddedWebAsset {
        path: "/",
        source_media_type: "text/html; charset=utf-8",
        media_type: "text/html; charset=utf-8",
        stored_representation: StoredRepresentation::Identity,
        source_bytes: 1_077,
        wire_bytes: 1_077,
        source_digest: digest("3ccd883461eb1c786c2418512f8cb6094a141a8459a2dd597fad00cccf5a3a2b"),
        wire_digest: digest("3ccd883461eb1c786c2418512f8cb6094a141a8459a2dd597fad00cccf5a3a2b"),
        bytes: INDEX,
    },
    EmbeddedWebAsset {
        path: "/alumina-bootstrap.js",
        source_media_type: "text/javascript; charset=utf-8",
        media_type: "text/javascript; charset=utf-8",
        stored_representation: StoredRepresentation::Identity,
        source_bytes: 16_235,
        wire_bytes: 16_235,
        source_digest: digest("2d3d556f85918dd4d4a93490b40a6d957c55bce5449274220a898171307fef18"),
        wire_digest: digest("2d3d556f85918dd4d4a93490b40a6d957c55bce5449274220a898171307fef18"),
        bytes: BOOTSTRAP,
    },
    EmbeddedWebAsset {
        path: "/alumina-brotli-decoder_bg.wasm",
        source_media_type: "application/wasm",
        media_type: "application/wasm",
        stored_representation: StoredRepresentation::Identity,
        source_bytes: 196_134,
        wire_bytes: 196_134,
        source_digest: digest("8a656d9cb18dfce82838f06f6153005a6cfa0c22c3cf575ef5cf30932fb46cab"),
        wire_digest: digest("8a656d9cb18dfce82838f06f6153005a6cfa0c22c3cf575ef5cf30932fb46cab"),
        bytes: DECODER_WASM,
    },
    EmbeddedWebAsset {
        path: "/alumina-interface.js.br",
        source_media_type: "text/javascript; charset=utf-8",
        media_type: "application/octet-stream",
        stored_representation: StoredRepresentation::BrotliRfc7932Q11W23,
        source_bytes: 91_816,
        wire_bytes: 10_909,
        source_digest: digest("4f0d819019f81df95b324a7f9a521effeb1c7d95ca56172be6b3af7e6c7f192e"),
        wire_digest: digest("5d6515aa29962f29b17b25496c0911c3ba9b4ca619fe9fdbaef60c35f55b10c3"),
        bytes: MODULE_BROTLI,
    },
    EmbeddedWebAsset {
        path: "/alumina-interface_bg.wasm.br",
        source_media_type: "application/wasm",
        media_type: "application/octet-stream",
        stored_representation: StoredRepresentation::BrotliRfc7932Q11W23,
        source_bytes: 8_421_767,
        wire_bytes: 2_820_967,
        source_digest: digest("b9670ad660146faa860bd1c7ee086e32da9b174f333fec3c161e6f11dd4ff8d9"),
        wire_digest: digest("9c6310d1993a7facbfd97d84be6185b20cb72af2d6997433e3bee40b1e20a415"),
        bytes: WASM_BROTLI,
    },
    EmbeddedWebAsset {
        path: "/alumina-worker.js",
        source_media_type: "text/javascript; charset=utf-8",
        media_type: "text/javascript; charset=utf-8",
        stored_representation: StoredRepresentation::Identity,
        source_bytes: 678,
        wire_bytes: 678,
        source_digest: digest("2d23324fa4fe34169abcc34046dcbcadbd13a02b99958f465ab3878a709c9a75"),
        wire_digest: digest("2d23324fa4fe34169abcc34046dcbcadbd13a02b99958f465ab3878a709c9a75"),
        bytes: WORKER,
    },
    EmbeddedWebAsset {
        path: "/favicon.ico",
        source_media_type: "image/x-icon",
        media_type: "image/x-icon",
        stored_representation: StoredRepresentation::Identity,
        source_bytes: 196,
        wire_bytes: 196,
        source_digest: digest("311f2089f900726358e69d1c490236942ea17aa418f198764a5662c8eaeeb5af"),
        wire_digest: digest("311f2089f900726358e69d1c490236942ea17aa418f198764a5662c8eaeeb5af"),
        bytes: FAVICON,
    },
    EmbeddedWebAsset {
        path: "/alumina-web-bundle.toml",
        source_media_type: "text/plain; charset=utf-8",
        media_type: "text/plain; charset=utf-8",
        stored_representation: StoredRepresentation::Identity,
        source_bytes: 2_755,
        wire_bytes: 2_755,
        source_digest: WEB_BUNDLE_DIGEST,
        wire_digest: WEB_BUNDLE_DIGEST,
        bytes: BUNDLE_MANIFEST,
    },
];
