[alias]
xtask = "run --package xtask --"

[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --monitor --chip esp32s3"
rustflags = [
    "-C",
    "link-arg=-nostartfiles",
    "-C",
    "link-arg=-Tdefmt.x",
]

[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor --chip esp32"
rustflags = [
    "-C",
    "link-arg=-nostartfiles",
    "-C",
    "link-arg=-Tdefmt.x",
]

[unstable]
build-std = ["alloc", "core"]
