[package]
name = "board-t-lora-pager"
description = "Typed compile-time current LILYGO T-LoRa Pager board stub"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
alumina-board.workspace = true
alumina-protocol.workspace = true

[dev-dependencies]
alumina-capability.workspace = true

[lints]
workspace = true
