[package]
name = "board-mks-tinybee"
description = "Typed compile-time MKS TinyBee V1.x board package"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
alumina-board.workspace = true
alumina-protocol.workspace = true

[lints]
workspace = true
